# Basic Information 
title: Jiabing Yang
position: Undergraduate Student
affiliation: University of Electronic Science and Technology of China
affiliation_link: https://www.uestc.edu.cn/
affiliation_logo: ./assets/img/university-logo-small-horizontal-white-156eae9527.svg
email: jiabingyang01@gmail.com
email2: yangjiabing0405@163.com

# Search Engine Optimization (SEO)
keywords: yaoyao liu, liu yaoyao, yaoyaoliu, liuyaoyao
canonical: https://www.cs.jhu.edu/~yyliu/
description: Yaoyao Liu is a postdoctoral fellow at Johns Hopkins University. His research lies in meta-learning, incremental learning, and image generation.

# The option is used to enable the Johns Hopkins template.
enable_hopkins_logo: true

# The option is used to show the last update time.
enable_last_update: false

# Links
link_type: icon #text/icon
google_scholar: https://scholar.google.com/
github_link: https://github.com/jiabingyang01/
cv_link: assets/files/curriculum_vitae.pdf
linkedin: https://www.linkedin.com/in/
twitter: https://twitter.com/

# Images 
avatar: ./assets/img/avatar.png
favicon: ./assets/img/favicon.png
favicon_dark: ./assets/img/favicon-dark.png

# Footnotes
# footnote: Feel free to use my website's source code.
# footnote_link: https://github.com/yaoyao-liu/minimal-light

# Analytics
# Please remove the following lines about analytics services if you fork my project. 
# Otherwise, the analytics information of your website will be recorded to my ClustrMaps accounts.
# clustrmaps_id: CJD8XwsJhSyQ6sbsU-Gw0cNcUlbah7KW3xvHN2QlwW0

# The following files will be removed from the generated website.
exclude:
  - build.sh
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - CNAME
